module Test exposing (..)

import Browser
import Html exposing (Html, button, div, text)
import Debug exposing (toString)

import Svg.Parser as Sp

main = Browser.sandbox {
         init = init
       , update = update
       , view = view
       }

init : ()
init = ()

update : () -> () -> ()
update _ _ = ()

view : () -> Html ()
view _ =
    text (Sp.parse svg
         |> toString)

svg : String
svg = """
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Title: %3 Pages: 1 -->
<svg width="134pt" height="188pt"
 viewBox="0.00 0.00 134.00 188.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 184)">
</g>
</svg>
"""
